// <auto-generated />
using System;
using Calculator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Calculator.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20200120182200_DataAnnotations")]
    partial class DataAnnotations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Calculator.Models.CertificateOfDeposit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PortfolioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("CertificateOfDeposits");

                    b.HasData(
                        new
                        {
                            Id = "1a1cd8bc-7722-4800-adb9-8f44cba15e61",
                            AccountNumber = 123456789,
                            DateCreated = new DateTime(2020, 1, 20, 12, 22, 0, 52, DateTimeKind.Local).AddTicks(4357),
                            InterestRate = 5m,
                            PortfolioId = "62a8842a-2feb-4330-8860-d1d0b28bcc5b",
                            Term = 12,
                            Type = "Normal"
                        });
                });

            modelBuilder.Entity("Calculator.Models.CreditCard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Income")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PortfolioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("UsageByPercentage")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("CreditCards");

                    b.HasData(
                        new
                        {
                            Id = "e87f3a08-d430-49ab-97d1-75eb2b5f2c88",
                            AccountNumber = 123321123,
                            Balance = 500m,
                            DateCreated = new DateTime(2020, 1, 20, 12, 22, 0, 52, DateTimeKind.Local).AddTicks(7041),
                            Income = 1123m,
                            InterestRate = 17m,
                            PortfolioId = "62a8842a-2feb-4330-8860-d1d0b28bcc5b",
                            Type = "Normal",
                            UsageByPercentage = 50m
                        });
                });

            modelBuilder.Entity("Calculator.Models.Deposit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("AverageBalance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PortfolioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Deposits");

                    b.HasData(
                        new
                        {
                            Id = "fd665f7d-ac47-469e-9ec0-b37cc6b0602a",
                            AccountNumber = 321321321,
                            AverageBalance = 5432m,
                            Cost = 500m,
                            DateCreated = new DateTime(2020, 1, 20, 12, 22, 0, 52, DateTimeKind.Local).AddTicks(9298),
                            InterestRate = 0.32m,
                            PortfolioId = "62a8842a-2feb-4330-8860-d1d0b28bcc5b",
                            Type = "Normal"
                        });
                });

            modelBuilder.Entity("Calculator.Models.Loan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Income")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PortfolioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = "7b88a90e-e340-4f18-8121-92e4f1d8a294",
                            AccountNumber = 54323453,
                            Balance = 9080m,
                            DateCreated = new DateTime(2020, 1, 20, 12, 22, 0, 53, DateTimeKind.Local).AddTicks(1155),
                            Income = 500m,
                            InterestRate = 3.32m,
                            PortfolioId = "62a8842a-2feb-4330-8860-d1d0b28bcc5b",
                            Term = 48,
                            Type = "Car"
                        });
                });

            modelBuilder.Entity("Calculator.Models.Portfolio", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(280)")
                        .HasMaxLength(280);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Portfolios");

                    b.HasData(
                        new
                        {
                            Id = "62a8842a-2feb-4330-8860-d1d0b28bcc5b",
                            DateCreated = new DateTime(2020, 1, 20, 12, 22, 0, 49, DateTimeKind.Local).AddTicks(1917),
                            Name = "Nim Sum",
                            Type = "Normal"
                        });
                });

            modelBuilder.Entity("Calculator.Models.CertificateOfDeposit", b =>
                {
                    b.HasOne("Calculator.Models.Portfolio", null)
                        .WithMany("CertificateOfDeposits")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Calculator.Models.CreditCard", b =>
                {
                    b.HasOne("Calculator.Models.Portfolio", null)
                        .WithMany("CreditCards")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Calculator.Models.Deposit", b =>
                {
                    b.HasOne("Calculator.Models.Portfolio", null)
                        .WithMany("Deposits")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Calculator.Models.Loan", b =>
                {
                    b.HasOne("Calculator.Models.Portfolio", null)
                        .WithMany("Loans")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
